name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this solve? Why do you need this feature?
      placeholder: "I often find myself needing to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "I'd like AVA to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives?
      placeholder: "I've tried... but..."

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AVA would this affect?
      options:
        - Desktop GUI
        - Terminal UI
        - CLI
        - Core (Cortex/Medulla)
        - Memory System
        - API
        - Installer
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (for you)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Essential for my use case

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, examples, or other relevant information
